import { Router } from "express";
import { z } from "zod";
import pool from "../config/database_connection";
import { verifyAdminToken, type AuthenticatedRequest } from "../middlewares/authentication_middleware";
import { logActivity } from "../helpers/activityLog";

const router = Router();
router.use(verifyAdminToken);
const uuid = z.string().uuid();
const ageSchema = z.object({ name:z.string().trim().min(2).max(120), displayLabel:z.string().trim().min(1).max(120), minAge:z.number().int().min(1).max(130), maxAge:z.number().int().min(1).max(130), subtitle:z.string().trim().max(180).default(""), description:z.string().trim().max(2000).default(""), imageUrl:z.string().url().or(z.literal("")).optional() }).refine(v=>v.maxAge>=v.minAge,{message:"Maximum age must be greater than or equal to minimum age."});
const categorySchema = z.object({ ageGroupId:uuid, name:z.string().trim().min(2).max(120), description:z.string().trim().max(2000).default(""), imageUrl:z.string().url().or(z.literal("")).optional() });
const levelSchema = z.object({ categoryId:uuid, name:z.string().trim().min(1).max(120), levelNumber:z.number().int().min(1), description:z.string().trim().max(2000).default(""), imageUrl:z.string().url().or(z.literal("")).optional(), pointsPerQuestion:z.number().int().min(1).max(1000).default(10), timeLimitSeconds:z.number().int().min(5).max(600).default(30) });
const cardSchema=z.object({title:z.string().trim().min(1).max(120),tag:z.string().trim().max(120).default(""),description:z.string().trim().max(2000).default(""),imageUrl:z.string().url(),programType:z.enum(["games","learn"]).optional()});
const itemSchema=cardSchema.extend({programId:uuid,parentId:uuid.nullable().optional(),itemType:z.enum(["section","grade","subject","topic","level"]),sortOrder:z.number().int().min(0).default(0)});
const learnQuestionSchema=z.object({questionText:z.string().trim().min(5).max(10000),explanation:z.string().trim().max(5000).default(""),status:z.enum(["draft","published"]).default("published"),options:z.array(z.object({text:z.string().trim().min(1).max(1000),isCorrect:z.boolean()})).length(4).refine(x=>x.filter(o=>o.isCorrect).length===1,"Select exactly one correct answer.")});
const invalid = (res:any, issues:any) => res.status(400).json({success:false,errors:issues});

router.get("/age-groups", async (_req,res) => { const r=await pool.query(`SELECT a.*,COUNT(DISTINCT c.id)::int category_count,COUNT(DISTINCT l.id)::int level_count FROM age_groups a LEFT JOIN game_categories c ON c.age_group_id=a.id LEFT JOIN game_levels l ON l.category_id=c.id GROUP BY a.id ORDER BY a.min_age`); res.json({success:true,ageGroups:r.rows}); });
router.post("/age-groups", async (req:AuthenticatedRequest,res) => { const v=ageSchema.safeParse(req.body); if(!v.success)return invalid(res,v.error.issues); const d=v.data; try { const r=await pool.query(`INSERT INTO age_groups(name,display_label,min_age,max_age,subtitle,description,image_url) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[d.name,d.displayLabel,d.minAge,d.maxAge,d.subtitle,d.description,d.imageUrl||null]); await logActivity({eventType:"catalog.age_group_created",title:"Age group created",description:`${d.name} was created`,metadata:{id:r.rows[0].id}}); res.status(201).json({success:true,ageGroup:r.rows[0]}); } catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"That age range already exists.":"Age group could not be created."});} });
router.put("/age-groups/:id", async (req,res) => { if(!uuid.safeParse(req.params.id).success)return invalid(res,[{message:"Invalid age group."}]); const v=ageSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`UPDATE age_groups SET name=$1,display_label=$2,min_age=$3,max_age=$4,subtitle=$5,description=$6,image_url=$7,updated_at=NOW() WHERE id=$8 RETURNING *`,[d.name,d.displayLabel,d.minAge,d.maxAge,d.subtitle,d.description,d.imageUrl||null,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Age group not found."});await logActivity({eventType:"catalog.age_group_updated",title:"Age group updated",description:`${d.name} was updated`});res.json({success:true,ageGroup:r.rows[0]}); });
router.delete("/age-groups/:id", async (req,res) => { if(!uuid.safeParse(req.params.id).success)return invalid(res,[{message:"Invalid age group."}]);const r=await pool.query("DELETE FROM age_groups WHERE id=$1 RETURNING name",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Age group not found."});await logActivity({eventType:"catalog.age_group_deleted",title:"Age group deleted",description:`${r.rows[0].name} and its contents were deleted`});res.json({success:true,message:"Age group deleted."}); });

router.get("/age-groups/:id/categories", async (req,res) => { const r=await pool.query(`SELECT c.*,COUNT(l.id)::int level_count FROM game_categories c LEFT JOIN game_levels l ON l.category_id=c.id WHERE c.age_group_id=$1 GROUP BY c.id ORDER BY c.created_at`,[req.params.id]);res.json({success:true,categories:r.rows}); });
router.post("/categories", async (req,res) => { const v=categorySchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;try{const r=await pool.query(`INSERT INTO game_categories(age_group_id,name,description,image_url) VALUES($1,$2,$3,$4) RETURNING *`,[d.ageGroupId,d.name,d.description,d.imageUrl||null]);await logActivity({eventType:"catalog.category_created",title:"Category created",description:`${d.name} was created`});res.status(201).json({success:true,category:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"This category already exists in the age group.":"Category could not be created."});} });
router.put("/categories/:id", async (req,res) => { const v=categorySchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`UPDATE game_categories SET age_group_id=$1,name=$2,description=$3,image_url=$4,updated_at=NOW() WHERE id=$5 RETURNING *`,[d.ageGroupId,d.name,d.description,d.imageUrl||null,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Category not found."});await logActivity({eventType:"catalog.category_updated",title:"Category updated",description:`${d.name} was updated`});res.json({success:true,category:r.rows[0]}); });
router.delete("/categories/:id", async (req,res) => { const r=await pool.query("DELETE FROM game_categories WHERE id=$1 RETURNING name",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Category not found."});await logActivity({eventType:"catalog.category_deleted",title:"Category deleted",description:`${r.rows[0].name} and its levels were deleted`});res.json({success:true,message:"Category deleted."}); });

router.get("/categories/:id/levels", async (req,res) => { const r=await pool.query(`SELECT l.*,COUNT(q.id)::int question_count,COUNT(q.id) FILTER (WHERE q.status='published')::int published_question_count FROM game_levels l LEFT JOIN questions q ON q.level_id=l.id WHERE l.category_id=$1 GROUP BY l.id ORDER BY l.level_number`,[req.params.id]);res.json({success:true,levels:r.rows}); });
router.post("/levels", async (req,res) => { const v=levelSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;try{const r=await pool.query(`INSERT INTO game_levels(category_id,name,level_number,description,image_url,points_per_question,time_limit_seconds) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[d.categoryId,d.name,d.levelNumber,d.description,d.imageUrl||null,d.pointsPerQuestion,d.timeLimitSeconds]);await logActivity({eventType:"catalog.level_created",title:"Level created",description:`${d.name} was created`});res.status(201).json({success:true,level:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"That level number already exists.":"Level could not be created."});} });
router.put("/levels/:id", async (req,res) => { const v=levelSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`UPDATE game_levels SET category_id=$1,name=$2,level_number=$3,description=$4,image_url=$5,points_per_question=$6,time_limit_seconds=$7,updated_at=NOW() WHERE id=$8 RETURNING *`,[d.categoryId,d.name,d.levelNumber,d.description,d.imageUrl||null,d.pointsPerQuestion,d.timeLimitSeconds,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Level not found."});await logActivity({eventType:"catalog.level_updated",title:"Level updated",description:`${d.name} was updated`});res.json({success:true,level:r.rows[0]}); });
router.delete("/levels/:id", async (req,res) => { const r=await pool.query("DELETE FROM game_levels WHERE id=$1 RETURNING name",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Level not found."});await logActivity({eventType:"catalog.level_deleted",title:"Level deleted",description:`${r.rows[0].name} was deleted`});res.json({success:true,message:"Level deleted."}); });

router.get("/programs",async(_req,res)=>{const r=await pool.query(`SELECT p.*,COUNT(i.id)::int item_count FROM learning_programs p LEFT JOIN learning_items i ON i.program_id=p.id GROUP BY p.id ORDER BY p.created_at`);res.json({success:true,programs:r.rows})});
router.post("/programs",async(req,res)=>{const v=cardSchema.extend({programType:z.enum(["games","learn"])}).safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;try{const r=await pool.query(`INSERT INTO learning_programs(title,slug,tag,description,image_url,program_type) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[d.title,d.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),d.tag,d.description,d.imageUrl,d.programType]);res.status(201).json({success:true,program:r.rows[0]})}catch{res.status(409).json({success:false,message:"A program with that title already exists."})}});
router.put("/programs/:id",async(req,res)=>{const v=cardSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`UPDATE learning_programs SET title=$1,tag=$2,description=$3,image_url=$4,updated_at=NOW() WHERE id=$5 RETURNING *`,[d.title,d.tag,d.description,d.imageUrl,req.params.id]);res.json({success:true,program:r.rows[0]})});
router.delete("/programs/:id",async(req,res)=>{await pool.query(`DELETE FROM learning_programs WHERE id=$1`,[req.params.id]);res.json({success:true})});
router.get("/learning-items",async(req,res)=>{const r=await pool.query(`SELECT i.*,COUNT(DISTINCT c.id)::int child_count,COUNT(DISTINCT q.id)::int question_count FROM learning_items i LEFT JOIN learning_items c ON c.parent_id=i.id LEFT JOIN learning_questions q ON q.level_id=i.id WHERE i.program_id=$1 AND i.parent_id IS NOT DISTINCT FROM $2::uuid GROUP BY i.id ORDER BY i.sort_order,i.created_at`,[req.query.programId,req.query.parentId||null]);res.json({success:true,items:r.rows})});
router.get("/learning-items/:id",async(req,res)=>{const r=await pool.query(`SELECT * FROM learning_items WHERE id=$1`,[req.params.id]);res.json({success:true,item:r.rows[0]})});
router.post("/learning-items",async(req,res)=>{const v=itemSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`INSERT INTO learning_items(program_id,parent_id,item_type,title,tag,description,image_url,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[d.programId,d.parentId||null,d.itemType,d.title,d.tag,d.description,d.imageUrl,d.sortOrder]);res.status(201).json({success:true,item:r.rows[0]})});
router.put("/learning-items/:id",async(req,res)=>{const v=itemSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const d=v.data;const r=await pool.query(`UPDATE learning_items SET title=$1,tag=$2,description=$3,image_url=$4,sort_order=$5,updated_at=NOW() WHERE id=$6 RETURNING *`,[d.title,d.tag,d.description,d.imageUrl,d.sortOrder,req.params.id]);res.json({success:true,item:r.rows[0]})});
router.delete("/learning-items/:id",async(req,res)=>{await pool.query(`DELETE FROM learning_items WHERE id=$1`,[req.params.id]);res.json({success:true})});
router.get("/learning-items/:id/questions",async(req,res)=>{const r=await pool.query(`SELECT q.*,COALESCE(json_agg(json_build_object('id',o.id,'text',o.option_text,'isCorrect',o.is_correct) ORDER BY o.option_order) FILTER(WHERE o.id IS NOT NULL),'[]') options FROM learning_questions q LEFT JOIN learning_question_options o ON o.question_id=q.id WHERE q.level_id=$1 GROUP BY q.id ORDER BY q.created_at`,[req.params.id]);res.json({success:true,questions:r.rows})});
router.post("/learning-items/:id/questions",async(req,res)=>{const v=learnQuestionSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const client=await pool.connect();try{await client.query("BEGIN");const q=await client.query(`INSERT INTO learning_questions(level_id,question_text,explanation,status) VALUES($1,$2,$3,$4) RETURNING *`,[req.params.id,v.data.questionText,v.data.explanation,v.data.status]);for(let i=0;i<4;i++){const o=v.data.options[i]!;await client.query(`INSERT INTO learning_question_options(question_id,option_order,option_text,is_correct) VALUES($1,$2,$3,$4)`,[q.rows[0].id,i,o.text,o.isCorrect])}await client.query("COMMIT");res.status(201).json({success:true})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}});
router.put("/learning-questions/:id",async(req,res)=>{const v=learnQuestionSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error.issues);const client=await pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE learning_questions SET question_text=$1,explanation=$2,status=$3,updated_at=NOW() WHERE id=$4`,[v.data.questionText,v.data.explanation,v.data.status,req.params.id]);await client.query(`DELETE FROM learning_question_options WHERE question_id=$1`,[req.params.id]);for(let i=0;i<4;i++){const o=v.data.options[i]!;await client.query(`INSERT INTO learning_question_options(question_id,option_order,option_text,is_correct) VALUES($1,$2,$3,$4)`,[req.params.id,i,o.text,o.isCorrect])}await client.query("COMMIT");res.json({success:true})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}});
router.delete("/learning-questions/:id",async(req,res)=>{await pool.query(`DELETE FROM learning_questions WHERE id=$1`,[req.params.id]);res.json({success:true})});

export default router;
