import { Router } from "express";
import crypto from "node:crypto";
import { z } from "zod";
import pool from "../config/database_connection";
import { verifyAdminToken, verifyPlayerToken, type AuthenticatedRequest } from "../middlewares/authentication_middleware";
import { logActivity } from "../helpers/activityLog";
import { recordCoinTransaction } from "../services/coin_service";
import { completeCoinPurchase, createCoinCheckout, validFlutterwaveSignature } from "../services/flutterwave_service";
import { redeemAirtime } from "../services/airtime_service";

const router = Router();
const uuid = z.string().uuid();
const packageSchema = z.object({ name:z.string().trim().min(2).max(120), description:z.string().trim().max(500).default(""), coins:z.number().int().positive().max(10000000), priceMinor:z.number().int().min(0).max(1000000000), currency:z.string().trim().length(3).transform(v=>v.toUpperCase()).default("NGN"), isActive:z.boolean().default(true), sortOrder:z.number().int().min(0).max(10000).default(0) });
const ruleSchema = z.object({ name:z.string().trim().min(2).max(120), eventKey:z.string().trim().regex(/^[a-z0-9._-]+$/,{message:"Use a short event name; spaces will be converted to underscores."}).max(80), type:z.enum(["reward","deduction"]), amount:z.number().int().positive().max(1000000), frequency:z.enum(["once","daily","weekly","per_event"]).default("per_event"), description:z.string().trim().max(500).default(""), isActive:z.boolean().default(true) });
const adjustmentSchema = z.object({ userId:uuid.optional(), userIds:z.array(uuid).min(1).max(500).optional(), type:z.enum(["reward","deduction"]), amount:z.number().int().positive().max(1000000), description:z.string().trim().min(3).max(500), reference:z.string().trim().max(120).optional() }).refine(v=>Boolean(v.userId)!==Boolean(v.userIds),{message:"Provide either userId or userIds.",path:["userIds"]});
const gameplaySettingsSchema = z.object({ passingScorePercent:z.number().int().min(0).max(100), maxLives:z.number().int().min(1).max(10), refillCoinCost:z.number().int().positive().max(1000000) });
const invalid=(res:any,error:any)=>res.status(400).json({success:false,errors:error.issues});
const paging=(query:any)=>({ page:Math.max(1,Number(query.page)||1), limit:Math.min(100,Math.max(1,Number(query.limit)||20)) });
const purchaseSchema = z.object({ packageId: uuid });
const verifyPurchaseSchema = z.object({ transactionId: z.coerce.number().int().positive(), txRef: z.string().trim().min(1).max(160) });
const airtimePurchaseSchema = z.object({ phone:z.string().trim().min(10).max(20), network:z.enum(["MTN","AIRTEL","GLO","9MOBILE"]), amount:z.number().int().min(1).max(1000000), clientReference:uuid });
const airtimeSettingsSchema = z.object({ pointsPerNaira:z.number().int().min(1).max(1000000), minimumAmount:z.number().int().min(1).max(1000000), maximumAmount:z.number().int().min(1).max(1000000), isEnabled:z.boolean() }).refine(v=>v.minimumAmount<=v.maximumAmount,{message:"Minimum amount cannot exceed maximum amount.",path:["minimumAmount"]});

router.get("/coins/packages", async (_req,res) => { const r=await pool.query("SELECT id,name,description,coins,price_minor,currency,sort_order FROM coin_packages WHERE is_active=true ORDER BY sort_order,coins"); res.json({success:true,packages:r.rows}); });
router.get("/coins/me", verifyPlayerToken, async (req:AuthenticatedRequest,res) => { const r=await pool.query("SELECT coins_count FROM users WHERE id=$1",[req.user!.id]); res.json({success:true,balance:Number(r.rows[0]?.coins_count||0)}); });
router.get("/coins/me/transactions", verifyPlayerToken, async (req:AuthenticatedRequest,res) => { const {page,limit}=paging(req.query); const count=await pool.query("SELECT COUNT(*)::int total FROM coin_transactions WHERE user_id=$1",[req.user!.id]); const r=await pool.query(`SELECT t.id,t.type,t.amount,t.balance_after,t.description,t.reference,t.created_at,
  COALESCE(r.name, NULLIF(t.metadata->>'eventKey','')) action_name
  FROM coin_transactions t
  LEFT JOIN coin_rules r ON r.id=t.rule_id
  WHERE t.user_id=$1 ORDER BY t.created_at DESC LIMIT $2 OFFSET $3`,[req.user!.id,limit,(page-1)*limit]); res.json({success:true,transactions:r.rows,pagination:{page,limit,total:Number(count.rows[0].total)}}); });
router.get("/airtime", verifyPlayerToken, async (req:AuthenticatedRequest,res) => { const {page,limit}=paging(req.query); const [settings,count,history]=await Promise.all([pool.query("SELECT points_per_naira,minimum_amount_minor,maximum_amount_minor,is_enabled,updated_at FROM airtime_settings WHERE id=1"),pool.query("SELECT COUNT(*)::int total FROM airtime_redemptions WHERE user_id=$1",[req.user!.id]),pool.query("SELECT id,phone,network,points_used,points_per_naira,amount_minor,currency,reference,provider_reference,status,failure_reason,created_at,completed_at FROM airtime_redemptions WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2 OFFSET $3",[req.user!.id,limit,(page-1)*limit])]);res.json({success:true,settings:settings.rows[0],redemptions:history.rows,pagination:{page,limit,total:Number(count.rows[0].total)}}); });
router.post("/airtime/redemptions", verifyPlayerToken, async (req:AuthenticatedRequest,res) => { const v=airtimePurchaseSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error);try{const result=await redeemAirtime({userId:req.user!.id,...v.data});res.status(result.repeated?200:201).json({success:true,...result});}catch(e:any){res.status(e.status||500).json({success:false,message:e.message||"Airtime could not be purchased."});} });

router.post("/coins/purchases", verifyPlayerToken, async (req:AuthenticatedRequest,res) => {
  const parsed=purchaseSchema.safeParse(req.body);if(!parsed.success)return invalid(res,parsed.error);
  try{const checkout=await createCoinCheckout(req.user!.id,parsed.data.packageId);res.status(201).json({success:true,...checkout});}
  catch(e:any){res.status(e.status||500).json({success:false,message:e.message||"Payment could not be started."});}
});
router.post("/coins/purchases/verify", verifyPlayerToken, async (req:AuthenticatedRequest,res) => {
  const parsed=verifyPurchaseSchema.safeParse(req.body);if(!parsed.success)return invalid(res,parsed.error);
  try{const result=await completeCoinPurchase(parsed.data.transactionId,parsed.data.txRef,req.user!.id);res.json({success:true,...result});}
  catch(e:any){res.status(e.status||500).json({success:false,message:e.message||"Payment could not be verified."});}
});
router.post("/coins/flutterwave/webhook", async (req:any,res) => {
  const signature=req.header("flutterwave-signature");
  if(!validFlutterwaveSignature(req.rawBody,signature))return res.status(401).json({success:false});
  res.sendStatus(200);
  const transactionId=Number(req.body?.data?.id);
  if((req.body?.type==="charge.completed"||req.body?.event==="charge.completed")&&Number.isSafeInteger(transactionId)){
    completeCoinPurchase(transactionId).catch((error)=>console.error("Flutterwave webhook processing failed",{transactionId,message:error?.message}));
  }
});

const admin=Router(); admin.use(verifyAdminToken);
admin.get("/gameplay-settings",async(_req,res)=>{const r=await pool.query("SELECT passing_score_percent,max_lives,refill_coin_cost,updated_at FROM gameplay_settings WHERE id=1");res.json({success:true,settings:r.rows[0]});});
admin.put("/gameplay-settings",async(req,res)=>{const v=gameplaySettingsSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data;const r=await pool.query("UPDATE gameplay_settings SET passing_score_percent=$1,max_lives=$2,refill_coin_cost=$3,updated_at=NOW() WHERE id=1 RETURNING *",[d.passingScorePercent,d.maxLives,d.refillCoinCost]);await pool.query("UPDATE users SET lives_remaining=LEAST(lives_remaining,$1)",[d.maxLives]);await logActivity({eventType:"coins.gameplay_settings_updated",title:"Life deduction settings updated",description:`Failed scores below ${d.passingScorePercent}% lose a life; refills cost ${d.refillCoinCost} coins`});res.json({success:true,settings:r.rows[0]});});
admin.get("/packages",async(_req,res)=>{const r=await pool.query("SELECT * FROM coin_packages ORDER BY sort_order,coins");res.json({success:true,packages:r.rows});});
admin.post("/packages",async(req,res)=>{const v=packageSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data;try{const r=await pool.query("INSERT INTO coin_packages(name,description,coins,price_minor,currency,is_active,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[d.name,d.description,d.coins,d.priceMinor,d.currency,d.isActive,d.sortOrder]);await logActivity({eventType:"coins.package_created",title:"Coin package created",description:`${d.name} was created`});res.status(201).json({success:true,package:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"A package with that name already exists.":"Package could not be created."});}});
admin.put("/packages/:id",async(req,res)=>{if(!uuid.safeParse(req.params.id).success)return res.status(400).json({success:false,message:"Invalid package."});const v=packageSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data;try{const r=await pool.query("UPDATE coin_packages SET name=$1,description=$2,coins=$3,price_minor=$4,currency=$5,is_active=$6,sort_order=$7,updated_at=NOW() WHERE id=$8 RETURNING *",[d.name,d.description,d.coins,d.priceMinor,d.currency,d.isActive,d.sortOrder,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Package not found."});await logActivity({eventType:"coins.package_updated",title:"Coin package updated",description:`${d.name} was updated`});res.json({success:true,package:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"A package with that name already exists.":"Package could not be updated."});}});
admin.delete("/packages/:id",async(req,res)=>{const r=await pool.query("DELETE FROM coin_packages WHERE id=$1 RETURNING name",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Package not found."});await logActivity({eventType:"coins.package_deleted",title:"Coin package deleted",description:`${r.rows[0].name} was deleted`});res.json({success:true,message:"Package deleted."});});
admin.get("/rules",async(_req,res)=>{const r=await pool.query("SELECT * FROM coin_rules ORDER BY type,name");res.json({success:true,rules:r.rows});});
admin.post("/rules",async(req,res)=>{const v=ruleSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data;try{const r=await pool.query("INSERT INTO coin_rules(name,event_key,type,amount,frequency,description,is_active) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[d.name,d.eventKey,d.type,d.amount,d.frequency,d.description,d.isActive]);res.status(201).json({success:true,rule:r.rows[0]});}catch(e:any){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"A rule already exists for that event and type.":"Rule could not be created."});}});
admin.put("/rules/:id",async(req,res)=>{const v=ruleSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data;const r=await pool.query("UPDATE coin_rules SET name=$1,event_key=$2,type=$3,amount=$4,frequency=$5,description=$6,is_active=$7,updated_at=NOW() WHERE id=$8 RETURNING *",[d.name,d.eventKey,d.type,d.amount,d.frequency,d.description,d.isActive,req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Rule not found."});res.json({success:true,rule:r.rows[0]});});
admin.delete("/rules/:id",async(req,res)=>{const r=await pool.query("DELETE FROM coin_rules WHERE id=$1 RETURNING id",[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false,message:"Rule not found."});res.json({success:true,message:"Rule deleted."});});
admin.get("/transactions",async(req,res)=>{const {page,limit}=paging(req.query);const type=typeof req.query.type==="string"?req.query.type:"";const search=typeof req.query.search==="string"?req.query.search.trim():"";const values:any[]=[];const clauses:string[]=[];if(type){values.push(type);clauses.push(`t.type=$${values.length}`);}if(search){values.push(`%${search}%`);clauses.push(`(u.name ILIKE $${values.length} OR u.email ILIKE $${values.length} OR t.reference ILIKE $${values.length})`);}const where=clauses.length?`WHERE ${clauses.join(" AND ")}`:"";const count=await pool.query(`SELECT COUNT(*)::int total FROM coin_transactions t JOIN users u ON u.id=t.user_id ${where}`,values);values.push(limit,(page-1)*limit);const r=await pool.query(`SELECT t.*,u.name user_name,u.email user_email FROM coin_transactions t JOIN users u ON u.id=t.user_id ${where} ORDER BY t.created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);res.json({success:true,transactions:r.rows,pagination:{page,limit,total:Number(count.rows[0].total)}});});
admin.get("/airtime",async(req,res)=>{const {page,limit}=paging(req.query);const status=typeof req.query.status==="string"?req.query.status:"";const search=typeof req.query.search==="string"?req.query.search.trim():"";const values:any[]=[];const clauses:string[]=[];if(status){values.push(status);clauses.push(`a.status=$${values.length}`);}if(search){values.push(`%${search}%`);clauses.push(`(u.name ILIKE $${values.length} OR u.email ILIKE $${values.length} OR a.phone ILIKE $${values.length} OR a.reference ILIKE $${values.length})`);}const where=clauses.length?`WHERE ${clauses.join(" AND ")}`:"";const [settings,count,summary]=await Promise.all([pool.query("SELECT * FROM airtime_settings WHERE id=1"),pool.query(`SELECT COUNT(*)::int total FROM airtime_redemptions a JOIN users u ON u.id=a.user_id ${where}`,values),pool.query("SELECT COUNT(*)::int total,COUNT(*) FILTER (WHERE status='successful')::int successful,COUNT(*) FILTER (WHERE status='refunded')::int refunded,COALESCE(SUM(amount_minor) FILTER (WHERE status='successful'),0)::bigint amount_minor,COALESCE(SUM(points_used) FILTER (WHERE status='successful'),0)::bigint points_used FROM airtime_redemptions")]);values.push(limit,(page-1)*limit);const history=await pool.query(`SELECT a.*,u.name user_name,u.username,u.email user_email FROM airtime_redemptions a JOIN users u ON u.id=a.user_id ${where} ORDER BY a.created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);res.json({success:true,settings:settings.rows[0],summary:summary.rows[0],redemptions:history.rows,pagination:{page,limit,total:Number(count.rows[0].total)}});});
admin.put("/airtime/settings",async(req:AuthenticatedRequest,res)=>{const v=airtimeSettingsSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data;const r=await pool.query("UPDATE airtime_settings SET points_per_naira=$1,minimum_amount_minor=$2,maximum_amount_minor=$3,is_enabled=$4,updated_by=$5,updated_at=NOW() WHERE id=1 RETURNING *",[d.pointsPerNaira,d.minimumAmount*100,d.maximumAmount*100,d.isEnabled,req.user!.role==="super_admin"?null:req.user!.id]);await logActivity({eventType:"airtime.settings_updated",title:"Airtime conversion settings updated",description:`${d.pointsPerNaira} points = NGN 1; range NGN ${d.minimumAmount} to NGN ${d.maximumAmount}; ${d.isEnabled?"enabled":"disabled"}`,metadata:{settings:r.rows[0]}});res.json({success:true,settings:r.rows[0]});});
admin.post("/transactions",async(req:AuthenticatedRequest,res)=>{const v=adjustmentSchema.safeParse(req.body);if(!v.success)return invalid(res,v.error);const d=v.data,userIds=[...new Set(d.userIds||[d.userId!])].sort(),batchId=crypto.randomUUID(),client=await pool.connect();try{await client.query("BEGIN");const found=await client.query("SELECT id FROM users WHERE role='user' AND id=ANY($1::uuid[])",[userIds]);if(found.rowCount!==userIds.length)throw Object.assign(new Error("One or more selected players no longer exist."),{status:404});const transactions=[];for(const userId of userIds)transactions.push(await recordCoinTransaction({userId,type:d.type,amount:d.amount,description:d.description,reference:d.reference?`${d.reference}:${userId}`:`admin:${batchId}:${userId}`,createdBy:req.user!.role==="super_admin"?undefined:req.user!.id,metadata:{kind:"manual_admin_adjustment",batchId,adminId:req.user!.id,recipientCount:userIds.length}},client));await client.query("COMMIT");await logActivity({eventType:`coins.manual_${d.type}`,title:d.type==="reward"?"Players manually rewarded":"Player points manually withdrawn",description:d.description,metadata:{batchId,userIds,amount:d.amount,transactionIds:transactions.map(t=>t.id),adminId:req.user!.id}});res.status(201).json({success:true,batchId,count:transactions.length,transactions,transaction:transactions[0]});}catch(e:any){await client.query("ROLLBACK");res.status(e.code==="23505"?409:e.status||500).json({success:false,message:e.code==="23505"?"That transaction reference has already been used.":e.message||"Transactions could not be recorded. No balances were changed."});}finally{client.release();}});

router.use("/admin/coins",admin);
export default router;
