import { Router } from "express";
import pool from "../config/database_connection";
const router=Router();
router.get("/age-groups",async(_req,res)=>{const r=await pool.query(`SELECT a.*,COUNT(DISTINCT c.id)::int category_count FROM age_groups a LEFT JOIN game_categories c ON c.age_group_id=a.id GROUP BY a.id ORDER BY a.min_age`);res.json({success:true,ageGroups:r.rows})});
router.get("/age-groups/:id/categories",async(req,res)=>{const r=await pool.query(`SELECT c.*,COUNT(l.id)::int level_count FROM game_categories c LEFT JOIN game_levels l ON l.category_id=c.id WHERE c.age_group_id=$1 GROUP BY c.id ORDER BY c.created_at`,[req.params.id]);res.json({success:true,categories:r.rows})});
router.get("/categories/:id/levels",async(req,res)=>{const r=await pool.query("SELECT * FROM game_levels WHERE category_id=$1 ORDER BY level_number",[req.params.id]);res.json({success:true,levels:r.rows})});
router.get("/programs",async(_req,res)=>{const r=await pool.query(`SELECT * FROM learning_programs ORDER BY created_at`);res.json({success:true,programs:r.rows})});
router.get("/learning-items",async(req,res)=>{const r=await pool.query(`SELECT i.*,COUNT(c.id)::int child_count FROM learning_items i LEFT JOIN learning_items c ON c.parent_id=i.id WHERE i.program_id=$1 AND i.parent_id IS NOT DISTINCT FROM $2::uuid GROUP BY i.id ORDER BY i.sort_order,i.created_at`,[req.query.programId,req.query.parentId||null]);res.json({success:true,items:r.rows})});
router.get("/learning-items/:id/questions",async(req,res)=>{const r=await pool.query(`SELECT q.id,q.question_text,q.explanation,COALESCE(json_agg(json_build_object('id',o.id,'text',o.option_text,'isCorrect',o.is_correct) ORDER BY o.option_order),'[]') options FROM learning_questions q JOIN learning_question_options o ON o.question_id=q.id WHERE q.level_id=$1 AND q.status='published' GROUP BY q.id ORDER BY q.created_at`,[req.params.id]);res.json({success:true,questions:r.rows})});
export default router;
